#!/usr/bin/env python3

#*********************************************************************
#** Author: James G Wilson
#** Date: 5/29/2018
#** Description: ftclient
#**		 A simple file transfer client written in Python. To
#		 be used with the C program, ftclient.c.
#*********************************************************************
import sys
import socket

# minimum functions
# initiateContact
# makeRequest
# receive file functions

# Initiate contact with the server.
def initiateContact(server_host, server_port):
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	s.connect((server_host, int(server_port)))

	return s

def main():

	# Check for correct command line syntax.
	if len(sys.argv) < 5 or len(sys.argv) > 6:
		print("Usage ./ftclient <SERVER_HOST> <SERVER_PORT> <COMMAND> <FILENAME> <DATA_PORT>")
		exit(1)
	
	# Store and validate command line arguments.
	server_host = sys.argv[1]
	server_port = sys.argv[2]
	command = sys.argv[3]
	filename = ""
	data_port = 0

	if len(sys.argv) is 5: 
		data_port = sys.argv[4]
	elif len(sys.argv) is 6: 
		filename = sys.argv[4]
		data_port = int(sys.argv[5])

	if command not in ["-g", "-l"]:
		print("Invalid command. Valid commands are: -g or -l.")
		exit(1)
	
	# Establish control connection with server
	server_socket = initiateContact(server_host, server_port)

	#********LEFT OFF HERE************
	message = "Hello! from client :D"
	server_socket.send(message.encode())


if __name__ == "__main__":

	#execute only if run as a script
	main()
